version: '3'

services:
  healtha-auto-rebuild:
    build: .
    command: node main.js
    ports:
      - "4000:4000"  
    volumes:
      - .:/app       
    develop:
      watch:
        - action: rebuild
          path: .
          target: /app
          ignore:
            - node_modules/
